version: '3.8'
services:
  app:
    build: .
    env_file: .env
    depends_on:
      - db
    tty: true  # дозволяє взаємодію через термінал
    stdin_open: true
  db:
    image: postgres:15    
    environment:
      POSTGRES_DB: my-postgres
      POSTGRES_USER: artur
      POSTGRES_PASSWORD: postgress
    volumes:
      - ./db:/docker-entrypoint-initdb.d